{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  # Release Name: dev-order-service
  name: {{ .Values.app.labels.env }}-{{ .Release.Name }}-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.commonLabels" . | nindent 8}}
    spec:
      containers:
        {{- range .Values.deployment.containers }}
        - name: {{ .name }}
          image: {{ .image }}:{{ .tag | default "latest" }}
          imagePullPolicy: {{ .imagePullPolicy | default "Always" }}
          ports:
            {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- if .env }} 
          env:
            {{- range .env }}
            {{- if and .name .value }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- if .resources.requests }}
            requests:
              {{- if .resources.requests.cpu }}
              cpu: {{ .resources.requests.cpu }}
              {{- end }}
              {{- if .resources.requests.memory}}
              memory: {{ .resources.requests.memory }}
              {{- end }}
            {{- end }}
            {{- if .resources.limits }}
            limits:
              {{- if .resources.limits.cpu }}
              cpu: {{ .resources.limits.cpu }}
              {{- end }}
              {{- if .resources.limits.memory }}
              memory: {{ .resources.limits.memory }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
{{- end }}