apiVersion: v1
kind: Pod
metadata:
  name: dev-order-nginx-pod
  namespace: dev-order-ns
  labels:
    app: dev-order-pod
    env: dev
    project: ecommerce
    team: order-team
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "0.25"
        memory: "500Mi"
      limits:
        cpu: "0.5"
        memory: "1.0Gi"
