apiVersion: v1
kind: Service
metadata:
  name: dev-order-lb
  labels:
    env: dev
    project: ecommerce
    team: order-team
spec:
  selector:
    app: dev-order-pod
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
