apiVersion: v1
kind: Service
metadata:
  name: dev-order-nodeport
  labels:
    env: dev
    project: ecommerce
    team: order-team
spec:
  selector:
    app: dev-order-pod
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  type: NodePort
