apiVersion: v1
kind: Service
metadata:
  name: dev-order-svc
  namespace: dev-order-ns
  labels:
    env: dev
    project: ecommerce
    team: order-team
    release: {{ .Release.Name }}
spec:
  selector:
    {{- range .Values.service.containers }}
    app: {{}}