{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- toYaml .Values.app.labels | nindent 4 }}
spec:
  selector:
    app: {{ .Values.app.labels.app }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if and (eq $.Values.service.type "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- end }}
