######################################
# 공통 메타 Configuration
######################################
app:
  labels:
    env: dev

######################################
# Deployment Configuration
######################################
deployment:
  enabled: true
  replicaCount: 3
  containers:
  - name: user-service-api
    image: youngmin1085/user-service
    tag: latest
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    resources:
      requests:
        cpu: "0.5"
        memory: "1Gi"
      limits:
        cpu: "0.75"
        memory: "1.5Gi"

######################################
# Service Configuration
######################################
service:
  enabled: true
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
