# -------------------------------------------------------------------
# Deployment 설정
# -------------------------------------------------------------------
deployment:
  nameSuffix: deploy
  labels:
    app: dev-order-pod
    env: dev
    project: ecommerce
    team: order-team
  replicaCount: 2
  containers:
    - name: dev-order-service-api
      image:
        repository: 842675972665.dkr.ecr.ap-northeast-2.amazonaws.com/order-service
        tag: latest
        pullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 8080
      resources:
        requests:
          cpu: "0.25"
          memory: "500Mi"
        limits:
          cpu: "0.5"
          memory: "1Gi"
      env:
        - name: SPRING_PROFILES_ACTIVE  
          value: dev