######################################
# Common Config
######################################
app:
  labels:
    app: order-service
    env: local
    project: ecommerce
    team: order-team

######################################
# Deployment Config
######################################
deployment:
  enabled: true
  replicaCount: 2
  containers:
  - name: order-service-api
    image: youngmin1085/order-service
    tag: latest
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    resources:
      requests:
        cpu: "0.25"
        memory: "512Mi"
      limits:
        cpu: "0.5"
        memory: "1Gi"

######################################
# Service Config
######################################
service:
  enabled: true
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

######################################
# Ingress Config
######################################
ingress:
  enabled: true
  annotation:
    backend-protocol: "HTTP"
    proxy-connect-timeout: "10"
    proxy-read-timeout: "60"
    proxy-send-timeout: "60"
    proxy-body-size: "8m"
  ingressClassName: nginx-ingress-controller
  rules:
  - host: localhost
    http:
      paths:
      - path: /api/v1/orders
        pathType: Prefix
        backend:
          service:
            name: order-service
            ports:
              number: 8080
      - path: /api/v1/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            ports:
              number: 8080