######################################
# 공통 메타 Configuration
######################################
app:
  labels:
    env: prod

######################################
# Deployment Config
######################################
deployment:
  enabled: true
  replicaCount: 3
  containers:
  - name: order-service-api
    image: youngmin1085/order-service
    tag: latest
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8443
      protocol: TCP
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "1.5"
        memory: "2Gi"

######################################
# Service Config
######################################
service:
  enabled: true
  ports:
  - name: http
    port: 8443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP

######################################
# Ingress Config
######################################
ingress:
  enabled: true
  annotation:
    backendProtocol: "HTTP"
    proxyConnectTimeout: "10"
    proxyReadTimeout: "30"
    proxySendTimeout: "30"
    proxyBodySize: "8m"
  ingressClassName: "nginx"
  rules:
  - host: prod-order.ecommerce.co.kr
    http:
      paths:
      - path: /api/v1/orders
        pathType: Prefix
        backend:
          service:
            name: order-service-svc
            port:
              number: 8443
