######################################
# 공통 메타 Configuration
######################################
app:
  labels:
    env: prod

######################################
# Deployment Config
######################################
deployment:
  enabled: true
  replicaCount: 3
  containers:
  - name: order-service-api
    image: youngmin1085/order-service
    tag: latest
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8443
      protocol: TCP
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "1.5"
        memory: "2Gi"

######################################
# Service Config
######################################
service:
  enabled: true
  ports:
  - name: http
    port: 8443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP
