######################################
# 공통 메타 Configuration
######################################
app:
  labels:
    env: dev

######################################
# Deployment Config
######################################
deployment:
  enabled: true
  replicaCount: 3
  containers:
  - name: order-service-api
    image: youngmin1085/order-service
    tag: 1.0.0
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    resources:
      requests:
        cpu: "0.5"
        memory: "1Gi"
      limits:
        cpu: "0.75"
        memory: "1.5Gi"

######################################
# Service Config
######################################
service:
  enabled: true
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
