environments:
  dev: {}
  stg: {}
  prod: {}
---

releases:
- name: order-service
  namespace: "{{ .Environment.Name }}-order-ns"
  chart: "../charts/order-service"
  values:
  - "../charts/order-service/values.yaml"
  - "../charts/order-service/values-{{ .Environment.Name }}.yaml"

- name: user-service
  namespace: "{{ .Environment.Name }}-user-ns"
  chart: "../charts/user-service"
  values:
  - "../charts/user-service/values.yaml"
  - "../charts/user-service/values-{{ .Environment.Name }}.yaml"

- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.11.0
  values:
  - controller:
      hostNetwork: true
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      admissionWebhooks:
        enabled: false
