apiVersion: v1
kind: Service
metadata:
  name: dev-order-svc
  labels:
    env: dev
    project: ecommerce
    team: order-team
spec:
  selector:
    app: order-pod
    env: dev
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 80
    protocol: TCP
  type: ClusterIP
