apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-order-deploy
  namespace: dev-order-ns
  labels:
    env: dev
    project: ecommerce
    team: order-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-order-pod
  template:
    metadata:
      labels:
        app: dev-order-pod
    spec:
      containers:
      - name: order-service-api
        image: <your account>.dkr.ecr.ap-northeast-2.amazonaws.com/order-service
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.25"
            memory: "0.5Mi"
          limits:
            cpu: "0.5"
            memory: "0.75Mi"
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 5 # 컨테이너 시작 후 몇초 뒤부터 체크 시작할지 지정
          periodSeconds: 10 # health check 간격
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
