######################################
# 공통 메타 Configuration
######################################
app:
  namespace: dev-user-ns # TODO: values-dev.yaml 환경 분리 필요
  labels:
    app: user-service
    env: dev
    project: ecommerce
    team: user-team

######################################
# Deployment Configuration
######################################
deployment:
  enabled: true
  replicaCount: 2
  containers:
  - name: dev-user-api
    image: youngmin1085/user-service
    tag: latest
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    resources:
      requests:
        cpu: "0.25"
        memory: "512Mi"
      limits:
        cpu: "0.5"
        memory: "1Gi"

######################################
# Service Configuration
######################################
service:
  enabled: true
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
